samples:
  EV_K4me3_S1_R1_001_sample100: "../EV_K4me3_S1_R1_001_sample100.fastq"
  EV_input_S7_R1_001_sample100: "../EV_input_S7_R1_001_sample100.fastq"

download_fasta: False # if this is true, then the entry to 'fasta' wont matter, the result of this download will be used
fasta: "Homo_sapiens.GRCh37.dna_sm.primary_assembly.fa" # this should be set if 'download_fasta' is False

# only fill this in if you left fasta blank

genome: "hg19"

#aligner: "bwa-mem"
aligner: "bowtie2"
align_cores: 2

index: False

#duplicates: "mark"
duplicates: "rm"

peak_samplesheet_path: "sample_sheet_test.csv"

extra_peaks_args: " "
